server:
  port: 7000


pagehelper:
  helper-dialect: mysql
  params=count: countSql
  reasonable: true
  support-methods-arguments: true

spring:
  application:
    name: ERUKACONSUMER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tx_logger?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root

  servlet:
    multipart:
      enabled: true
      location: D:\workSpace\myProject\erukatest\fileInteraction
      file-size-threshold: 100MB
      max-file-size: 200MB

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

tx-lcn:
  ribbon:
    loadbalancer:
      dtx:
        enabled: true
  logger:
    enabled: true
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/tx_logger?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
logging:
  level:
    com.meikinfo.erukaconsumer.erukaconsumer: debug


eureka:
  client:
   service-url:
     defaultZone: http://localhost:8761/eureka/


