server:
  port: 8000


pagehelper:
  helper-dialect: mysql
  params=count: countSql
  reasonable: true
  support-methods-arguments: true

spring:
  application:
    name: ERUKAPROVIDE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tx_logger?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: localhost:9300
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
  mail:
    host: smtp.qq.com
    port: 465
    username: 1353208500@qq.com
    password: brklxjnawkjoifbj
    protocol: smtp
    test-connection: true
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: 1353208500@qq.com

  main:
    allow-bean-definition-overriding: true

tx-lcn:
  ribbon:
    loadbalancer:
      dtx:
        enabled: true
  logger:
    enabled: true
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/tx_logger?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root

logging:
  level:
    com.meikinfo.erukaprovide.erukaprovide: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
